project: EPCAPE     

serial:
    POPS: /dev/ttyUSB0   # PORT designation for POPS
    CCN:  /dev/ttyUSB1   # PORT designation for DMT CCN
    CPC:  /dev/ttyUSB2   # PORT designation for CPC

LJ:
    ID: -1               # ID of Labjack, -1 == first found
    AIN:                 # Designation of Ana
        RH: 0            # RH sensor humidity
        T: 1             # RH sensor temperatlog Inputs
        V: 2             # Ultravolt HV read 
        I: 3             # Ultravolt current read 
    FIO:
        counter1: 0      # FIO0 is a counter
        counter2: 1      # FIO1 is a counter
        Tick_DAC: 2      # FIO2 and FIO3 is a LJTick-DAC
    Tick_DAC:
        V:  2            # Vset is on second DAC port 

CPC:
    model: TSI3771       # CPC used in system

DMA:                     # Configuration of DMA
    model: TSILONG       # TSI Long Column
    Qsh: 5.0             # Sheath flow [L min-1]
    Qsa: 1.3             # Sample flow [L min-1]
    T: 22.0              # Temperature [degree C]
    p: 101315.0          # Pressure [Pa]